//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:56:39 PM CDT 
//


package edu.illinois.ncsa.gondola.types.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for my-proxy-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="my-proxy-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="server-uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="host-cert-dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="proxy-refresh-in-mins" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="proxy-margin-in-mins" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "my-proxy-type", propOrder = {
    "serverUri",
    "hostCertDir",
    "proxyRefreshInMins",
    "proxyMarginInMins"
})
public class MyProxyType {

    @XmlElement(name = "server-uri", required = true)
    protected String serverUri;
    @XmlElement(name = "host-cert-dir")
    protected String hostCertDir;
    @XmlElement(name = "proxy-refresh-in-mins", defaultValue = "60")
    protected int proxyRefreshInMins;
    @XmlElement(name = "proxy-margin-in-mins", defaultValue = "120")
    protected int proxyMarginInMins;

    /**
     * Gets the value of the serverUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerUri() {
        return serverUri;
    }

    /**
     * Sets the value of the serverUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerUri(String value) {
        this.serverUri = value;
    }

    /**
     * Gets the value of the hostCertDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostCertDir() {
        return hostCertDir;
    }

    /**
     * Sets the value of the hostCertDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostCertDir(String value) {
        this.hostCertDir = value;
    }

    /**
     * Gets the value of the proxyRefreshInMins property.
     * 
     */
    public int getProxyRefreshInMins() {
        return proxyRefreshInMins;
    }

    /**
     * Sets the value of the proxyRefreshInMins property.
     * 
     */
    public void setProxyRefreshInMins(int value) {
        this.proxyRefreshInMins = value;
    }

    /**
     * Gets the value of the proxyMarginInMins property.
     * 
     */
    public int getProxyMarginInMins() {
        return proxyMarginInMins;
    }

    /**
     * Sets the value of the proxyMarginInMins property.
     * 
     */
    public void setProxyMarginInMins(int value) {
        this.proxyMarginInMins = value;
    }

}
