version: "3.5"

services:
  # DataWolf application
  datawolf:
    image: datawolf/datawolf:latest
    volumes:
      - datawolf:/home/datawolf/data
    ports:
      - 8888:8888
    networks:
      - datawolf

networks:
  datawolf:

volumes:
  datawolf: