#! /bin/sh

start() {
  su -c "/usr/bin/java -Dlog4j.configuration=file:///home/datawolf/log4j.properties -jar /home/datawolf/jetty-runner.jar --port 9093 --out /home/datawolf/datawolf-yyyy_mm_dd.log /home/datawolf/jetty.xml" datawolf &
  echo $! > /var/run/datawolf.pid
}

stop() {
  pid=`cat /var/run/datawolf.pid`
  kill $pid
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
esac
exit 0
