//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:56:39 PM CDT 
//


package edu.illinois.ncsa.gondola.types.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.illinois.ncsa.gondola.types.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceConfig_QNAME = new QName("http://edu.illinois.ncsa.gondola/service", "service-config");
    private final static QName _JdbcAccess_QNAME = new QName("http://edu.illinois.ncsa.gondola/service", "jdbc-access");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.illinois.ncsa.gondola.types.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link InitializeType }
     * 
     */
    public InitializeType createInitializeType() {
        return new InitializeType();
    }

    /**
     * Create an instance of {@link DropType }
     * 
     */
    public DropType createDropType() {
        return new DropType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link DbcpType }
     * 
     */
    public DbcpType createDbcpType() {
        return new DbcpType();
    }

    /**
     * Create an instance of {@link DbcpType.Property }
     * 
     */
    public DbcpType.Property createDbcpTypeProperty() {
        return new DbcpType.Property();
    }

    /**
     * Create an instance of {@link MyProxyType }
     * 
     */
    public MyProxyType createMyProxyType() {
        return new MyProxyType();
    }

    /**
     * Create an instance of {@link AccessType }
     * 
     */
    public AccessType createAccessType() {
        return new AccessType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/service", name = "service-config")
    public JAXBElement<ServiceType> createServiceConfig(ServiceType value) {
        return new JAXBElement<ServiceType>(_ServiceConfig_QNAME, ServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/service", name = "jdbc-access")
    public JAXBElement<AccessType> createJdbcAccess(AccessType value) {
        return new JAXBElement<AccessType>(_JdbcAccess_QNAME, AccessType.class, null, value);
    }

}
