//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:56:39 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://edu.illinois.ncsa.gondola/service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.illinois.ncsa.gondola.types.service;
