//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:56:39 PM CDT 
//


package edu.illinois.ncsa.gondola.types.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for service-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="service-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="worker-pool" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="initialize-queue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="submit-queue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="update-queue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cancel-queue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="queue-refresh-in-secs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status-refresh-in-secs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="jdbc-access" type="{http://edu.illinois.ncsa.gondola/service}access-type"/>
 *         &lt;element name="myproxy-settings" type="{http://edu.illinois.ncsa.gondola/service}my-proxy-type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "service-type", propOrder = {
    "workerPool",
    "initializeQueue",
    "submitQueue",
    "updateQueue",
    "cancelQueue",
    "queueRefreshInSecs",
    "statusRefreshInSecs",
    "jdbcAccess",
    "myproxySettings"
})
public class ServiceType {

    @XmlElement(name = "worker-pool", defaultValue = "50")
    protected int workerPool;
    @XmlElement(name = "initialize-queue", defaultValue = "10")
    protected int initializeQueue;
    @XmlElement(name = "submit-queue", defaultValue = "10")
    protected int submitQueue;
    @XmlElement(name = "update-queue", defaultValue = "10")
    protected int updateQueue;
    @XmlElement(name = "cancel-queue", defaultValue = "10")
    protected int cancelQueue;
    @XmlElement(name = "queue-refresh-in-secs", defaultValue = "60")
    protected int queueRefreshInSecs;
    @XmlElement(name = "status-refresh-in-secs", defaultValue = "60")
    protected int statusRefreshInSecs;
    @XmlElement(name = "jdbc-access", required = true)
    protected AccessType jdbcAccess;
    @XmlElement(name = "myproxy-settings")
    protected MyProxyType myproxySettings;

    /**
     * Gets the value of the workerPool property.
     * 
     */
    public int getWorkerPool() {
        return workerPool;
    }

    /**
     * Sets the value of the workerPool property.
     * 
     */
    public void setWorkerPool(int value) {
        this.workerPool = value;
    }

    /**
     * Gets the value of the initializeQueue property.
     * 
     */
    public int getInitializeQueue() {
        return initializeQueue;
    }

    /**
     * Sets the value of the initializeQueue property.
     * 
     */
    public void setInitializeQueue(int value) {
        this.initializeQueue = value;
    }

    /**
     * Gets the value of the submitQueue property.
     * 
     */
    public int getSubmitQueue() {
        return submitQueue;
    }

    /**
     * Sets the value of the submitQueue property.
     * 
     */
    public void setSubmitQueue(int value) {
        this.submitQueue = value;
    }

    /**
     * Gets the value of the updateQueue property.
     * 
     */
    public int getUpdateQueue() {
        return updateQueue;
    }

    /**
     * Sets the value of the updateQueue property.
     * 
     */
    public void setUpdateQueue(int value) {
        this.updateQueue = value;
    }

    /**
     * Gets the value of the cancelQueue property.
     * 
     */
    public int getCancelQueue() {
        return cancelQueue;
    }

    /**
     * Sets the value of the cancelQueue property.
     * 
     */
    public void setCancelQueue(int value) {
        this.cancelQueue = value;
    }

    /**
     * Gets the value of the queueRefreshInSecs property.
     * 
     */
    public int getQueueRefreshInSecs() {
        return queueRefreshInSecs;
    }

    /**
     * Sets the value of the queueRefreshInSecs property.
     * 
     */
    public void setQueueRefreshInSecs(int value) {
        this.queueRefreshInSecs = value;
    }

    /**
     * Gets the value of the statusRefreshInSecs property.
     * 
     */
    public int getStatusRefreshInSecs() {
        return statusRefreshInSecs;
    }

    /**
     * Sets the value of the statusRefreshInSecs property.
     * 
     */
    public void setStatusRefreshInSecs(int value) {
        this.statusRefreshInSecs = value;
    }

    /**
     * Gets the value of the jdbcAccess property.
     * 
     * @return
     *     possible object is
     *     {@link AccessType }
     *     
     */
    public AccessType getJdbcAccess() {
        return jdbcAccess;
    }

    /**
     * Sets the value of the jdbcAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessType }
     *     
     */
    public void setJdbcAccess(AccessType value) {
        this.jdbcAccess = value;
    }

    /**
     * Gets the value of the myproxySettings property.
     * 
     * @return
     *     possible object is
     *     {@link MyProxyType }
     *     
     */
    public MyProxyType getMyproxySettings() {
        return myproxySettings;
    }

    /**
     * Sets the value of the myproxySettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link MyProxyType }
     *     
     */
    public void setMyproxySettings(MyProxyType value) {
        this.myproxySettings = value;
    }

}
