//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.21 at 08:05:26 AM CDT 
//


package edu.illinois.ncsa.gondola.types.submission;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for job-state-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="job-state-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="JOB_UNINITIALIZED"/>
 *     &lt;enumeration value="JOB_INIT_PENDING"/>
 *     &lt;enumeration value="JOB_INITIALIZED"/>
 *     &lt;enumeration value="JOB_SUBMIT_PENDING"/>
 *     &lt;enumeration value="JOB_SUBMITTED"/>
 *     &lt;enumeration value="JOB_QUEUED"/>
 *     &lt;enumeration value="JOB_RUNNING"/>
 *     &lt;enumeration value="JOB_SUSPENDED"/>
 *     &lt;enumeration value="JOB_CANCEL_REQUESTED"/>
 *     &lt;enumeration value="JOB_CANCEL_PENDING"/>
 *     &lt;enumeration value="JOB_CANCEL_FAILED"/>
 *     &lt;enumeration value="JOB_CANCELED"/>
 *     &lt;enumeration value="JOB_COMPLETED"/>
 *     &lt;enumeration value="JOB_INIT_FAILED"/>
 *     &lt;enumeration value="JOB_SUBMIT_FAILED"/>
 *     &lt;enumeration value="JOB_SUCCESS"/>
 *     &lt;enumeration value="JOB_FAILURE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum JobStateType {

    JOB_UNINITIALIZED,
    JOB_INIT_PENDING,
    JOB_INITIALIZED,
    JOB_SUBMIT_PENDING,
    JOB_SUBMITTED,
    JOB_QUEUED,
    JOB_RUNNING,
    JOB_SUSPENDED,
    JOB_CANCEL_REQUESTED,
    JOB_CANCEL_PENDING,
    JOB_CANCEL_FAILED,
    JOB_CANCELED,
    JOB_COMPLETED,
    JOB_INIT_FAILED,
    JOB_SUBMIT_FAILED,
    JOB_SUCCESS,
    JOB_FAILURE;

    public String value() {
        return name();
    }

    public static JobStateType fromValue(String v) {
        return valueOf(v);
    }

}
