//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.21 at 08:05:26 AM CDT 
//


package edu.illinois.ncsa.gondola.types.submission;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.illinois.ncsa.gondola.types.submission package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JobScript_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "job-script");
    private final static QName _JobErrorHandler_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "job-error-handler");
    private final static QName _JobStatusParser_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "job-status-parser");
    private final static QName _JobSubmission_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "job-submission");
    private final static QName _JobStatus_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "job-status");
    private final static QName _IdList_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "id-list");
    private final static QName _JobStatusList_QNAME = new QName("http://edu.illinois.ncsa.gondola/submission", "job-status-list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.illinois.ncsa.gondola.types.submission
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegexType }
     * 
     */
    public RegexType createRegexType() {
        return new RegexType();
    }

    /**
     * Create an instance of {@link LineType }
     * 
     */
    public LineType createLineType() {
        return new LineType();
    }

    /**
     * Create an instance of {@link JobStatusListType }
     * 
     */
    public JobStatusListType createJobStatusListType() {
        return new JobStatusListType();
    }

    /**
     * Create an instance of {@link ScriptType }
     * 
     */
    public ScriptType createScriptType() {
        return new ScriptType();
    }

    /**
     * Create an instance of {@link ExpressionGroupTranslatorType }
     * 
     */
    public ExpressionGroupTranslatorType createExpressionGroupTranslatorType() {
        return new ExpressionGroupTranslatorType();
    }

    /**
     * Create an instance of {@link StatusHandlerType }
     * 
     */
    public StatusHandlerType createStatusHandlerType() {
        return new StatusHandlerType();
    }

    /**
     * Create an instance of {@link ErrorHandlerType }
     * 
     */
    public ErrorHandlerType createErrorHandlerType() {
        return new ErrorHandlerType();
    }

    /**
     * Create an instance of {@link JobSubmissionType }
     * 
     */
    public JobSubmissionType createJobSubmissionType() {
        return new JobSubmissionType();
    }

    /**
     * Create an instance of {@link ParserType }
     * 
     */
    public ParserType createParserType() {
        return new ParserType();
    }

    /**
     * Create an instance of {@link JobStatusType }
     * 
     */
    public JobStatusType createJobStatusType() {
        return new JobStatusType();
    }

    /**
     * Create an instance of {@link IdListType }
     * 
     */
    public IdListType createIdListType() {
        return new IdListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScriptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "job-script")
    public JAXBElement<ScriptType> createJobScript(ScriptType value) {
        return new JAXBElement<ScriptType>(_JobScript_QNAME, ScriptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorHandlerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "job-error-handler")
    public JAXBElement<ErrorHandlerType> createJobErrorHandler(ErrorHandlerType value) {
        return new JAXBElement<ErrorHandlerType>(_JobErrorHandler_QNAME, ErrorHandlerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "job-status-parser")
    public JAXBElement<ParserType> createJobStatusParser(ParserType value) {
        return new JAXBElement<ParserType>(_JobStatusParser_QNAME, ParserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobSubmissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "job-submission")
    public JAXBElement<JobSubmissionType> createJobSubmission(JobSubmissionType value) {
        return new JAXBElement<JobSubmissionType>(_JobSubmission_QNAME, JobSubmissionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "job-status")
    public JAXBElement<JobStatusType> createJobStatus(JobStatusType value) {
        return new JAXBElement<JobStatusType>(_JobStatus_QNAME, JobStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "id-list")
    public JAXBElement<IdListType> createIdList(IdListType value) {
        return new JAXBElement<IdListType>(_IdList_QNAME, IdListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobStatusListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edu.illinois.ncsa.gondola/submission", name = "job-status-list")
    public JAXBElement<JobStatusListType> createJobStatusList(JobStatusListType value) {
        return new JAXBElement<JobStatusListType>(_JobStatusList_QNAME, JobStatusListType.class, null, value);
    }

}
