//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.21 at 08:05:26 AM CDT 
//


package edu.illinois.ncsa.gondola.types.submission;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for error-handler-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="error-handler-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stderr-warn" type="{http://edu.illinois.ncsa.gondola/submission}regex-type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stderr-error" type="{http://edu.illinois.ncsa.gondola/submission}regex-type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stdout-warn" type="{http://edu.illinois.ncsa.gondola/submission}regex-type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stdout-error" type="{http://edu.illinois.ncsa.gondola/submission}regex-type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "error-handler-type", propOrder = {
    "stderrWarn",
    "stderrError",
    "stdoutWarn",
    "stdoutError"
})
public class ErrorHandlerType {

    @XmlElement(name = "stderr-warn")
    protected List<RegexType> stderrWarn;
    @XmlElement(name = "stderr-error")
    protected List<RegexType> stderrError;
    @XmlElement(name = "stdout-warn")
    protected List<RegexType> stdoutWarn;
    @XmlElement(name = "stdout-error")
    protected List<RegexType> stdoutError;

    /**
     * Gets the value of the stderrWarn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stderrWarn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStderrWarn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegexType }
     * 
     * 
     */
    public List<RegexType> getStderrWarn() {
        if (stderrWarn == null) {
            stderrWarn = new ArrayList<RegexType>();
        }
        return this.stderrWarn;
    }

    /**
     * Gets the value of the stderrError property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stderrError property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStderrError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegexType }
     * 
     * 
     */
    public List<RegexType> getStderrError() {
        if (stderrError == null) {
            stderrError = new ArrayList<RegexType>();
        }
        return this.stderrError;
    }

    /**
     * Gets the value of the stdoutWarn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stdoutWarn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStdoutWarn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegexType }
     * 
     * 
     */
    public List<RegexType> getStdoutWarn() {
        if (stdoutWarn == null) {
            stdoutWarn = new ArrayList<RegexType>();
        }
        return this.stdoutWarn;
    }

    /**
     * Gets the value of the stdoutError property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stdoutError property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStdoutError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegexType }
     * 
     * 
     */
    public List<RegexType> getStdoutError() {
        if (stdoutError == null) {
            stdoutError = new ArrayList<RegexType>();
        }
        return this.stdoutError;
    }

}
