//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.21 at 08:05:26 AM CDT 
//


package edu.illinois.ncsa.gondola.types.submission;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parser-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parser-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expression" type="{http://edu.illinois.ncsa.gondola/submission}regex-type"/>
 *         &lt;element name="job-id-group" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="translator" type="{http://edu.illinois.ncsa.gondola/submission}expression-group-translator-type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="stderr" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parser-type", propOrder = {
    "expression",
    "jobIdGroup",
    "translator"
})
public class ParserType {

    @XmlElement(required = true)
    protected RegexType expression;
    @XmlElement(name = "job-id-group", defaultValue = "0")
    protected int jobIdGroup;
    protected List<ExpressionGroupTranslatorType> translator;
    @XmlAttribute
    protected Boolean stderr;

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link RegexType }
     *     
     */
    public RegexType getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegexType }
     *     
     */
    public void setExpression(RegexType value) {
        this.expression = value;
    }

    /**
     * Gets the value of the jobIdGroup property.
     * 
     */
    public int getJobIdGroup() {
        return jobIdGroup;
    }

    /**
     * Sets the value of the jobIdGroup property.
     * 
     */
    public void setJobIdGroup(int value) {
        this.jobIdGroup = value;
    }

    /**
     * Gets the value of the translator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the translator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTranslator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpressionGroupTranslatorType }
     * 
     * 
     */
    public List<ExpressionGroupTranslatorType> getTranslator() {
        if (translator == null) {
            translator = new ArrayList<ExpressionGroupTranslatorType>();
        }
        return this.translator;
    }

    /**
     * Gets the value of the stderr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStderr() {
        if (stderr == null) {
            return false;
        } else {
            return stderr;
        }
    }

    /**
     * Sets the value of the stderr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStderr(Boolean value) {
        this.stderr = value;
    }

}
