#! /bin/sh

start() {
  su -c "/usr/bin/java -Dlog4j.configuration=file:///home/cyberintegrator/log4j.properties -jar /home/cyberintegrator/jetty-runner.jar --port 9093 --out /home/cyberintegrator/cyberintegrator-yyyy-mm-dd.log /home/cyberintegrator/jetty.xml" cyberintegrator &
  echo $! > /var/run/cyberintegrator.pid
}

stop() {
  pid=`cat /var/run/cyberintegrator.pid`
  kill $pid
}

case "$1" in
  start)
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
esac
exit 0
