apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datawolf.fullname" . }}-config
  labels:
    {{- include "datawolf.labels" . | nindent 4 }}
data:
  log4j.properties: |-
    # Root logger option
    log4j.rootLogger=INFO, stdout

    # Detailed log levels
    log4j.logger.edu.illinois.ncsa.datawolf={{ .Values.loglevel }}
    log4j.logger.edu.illinois.ncsa.datawolf.Engine={{ .Values.loglevel }}

    # Direct log messages to stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.Target=System.out
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{ABSOLUTE} [%t] %5p %50.50c:%4L - %m%n
