{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datawolf.fullname" . }}-jobs
  labels:
    {{- include "datawolf.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "datawolf.fullname" . }}-jobs
  labels:
    {{- include "datawolf.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "datawolf.fullname" . }}-jobs
subjects:
  - name: {{ include "datawolf.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
{{- end }}
