//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.21 at 08:05:26 AM CDT 
//


package edu.illinois.ncsa.gondola.types.submission;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for status-handler-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="status-handler-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="command-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="command-args" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parser" type="{http://edu.illinois.ncsa.gondola/submission}parser-type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "status-handler-type", propOrder = {
    "commandPath",
    "commandArgs",
    "parser"
})
public class StatusHandlerType {

    @XmlElement(name = "command-path", required = true)
    protected String commandPath;
    @XmlElement(name = "command-args")
    protected String commandArgs;
    @XmlElement(required = true)
    protected ParserType parser;

    /**
     * Gets the value of the commandPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandPath() {
        return commandPath;
    }

    /**
     * Sets the value of the commandPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandPath(String value) {
        this.commandPath = value;
    }

    /**
     * Gets the value of the commandArgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandArgs() {
        return commandArgs;
    }

    /**
     * Sets the value of the commandArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandArgs(String value) {
        this.commandArgs = value;
    }

    /**
     * Gets the value of the parser property.
     * 
     * @return
     *     possible object is
     *     {@link ParserType }
     *     
     */
    public ParserType getParser() {
        return parser;
    }

    /**
     * Sets the value of the parser property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParserType }
     *     
     */
    public void setParser(ParserType value) {
        this.parser = value;
    }

}
