apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIubmNzYS5pbGxpbm9pcy5lZHUiOnsidXNlcm5hbWUiOiJyb2JvdCRpbmNvcmUra3ViZXJuZXRlcyIsInBhc3N3b3JkIjoieDl3bTRDRnA0UGdVenAzZTB6dENWSVRLeTJ4ZlVnSEEiLCJlbWFpbCI6ImRldm51bGwraW5jb3JlQG5jc2EuaWxsaW5vaXMuZWR1IiwiYXV0aCI6ImNtOWliM1FrYVc1amIzSmxLMnQxWW1WeWJtVjBaWE02ZURsM2JUUkRSbkEwVUdkVmVuQXpaVEI2ZEVOV1NWUkxlVEo0WmxWblNFRT0ifX19
